name: Build Vite Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Move build output to docs
        run: mv dist docs

      - name: Upload docs artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs
          
