name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your project's main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1  # Change this to your project's Node.js version

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build  # Adjust this command based on your Vite project's build script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist  # Change this to your project's build output directory
